### ISSUE TITLE
Julia interface

### ISSUE THREAD

**Issue by antoine-levitt** [whuang08/ROPTLIB#2]
Hi,

I'm having trouble using the Julia interface. Specifically, I'm using julia 0.6rc3, maybe that's incompatible?

1) am I correct that I need to use TP?=DriverJuliaProb in the makefile?
2) I had to change a few paths: there's no usr/ in my julia distribution, and julia.h is in include/julia/ instead of just include/

When I do make JuliaROPTLIB with this, I get
`
/home/antoine/ROPTLIB//test/DriverJuliaProb.cpp: In function ‘bool RJULIA::juliaInnerStop(ROPTLIB::Element*, ROPTLIB::Element*, double, double, double, const ROPTLIB::Problem*, const ROPTLIB::Solvers*)’:
/home/antoine/ROPTLIB//test/DriverJuliaProb.cpp:101:72: error: cannot convert ‘jl_datatype_t* {aka _jl_datatype_t*}’ to ‘jl_value_t* {aka _jl_value_t*}’ for argument ‘1’ to ‘jl_value_t* jl_apply_array_type(jl_value_t*, size_t)’
         jl_value_t* array_type = jl_apply_array_type(jl_float64_type, 1);
                                                                        ^
/home/antoine/ROPTLIB//test/DriverJuliaProb.cpp: In function ‘double RJULIA::juliaLinesearchInput(integer, ROPTLIB::Element*, ROPTLIB::Element*, double, double, const ROPTLIB::Problem*, const ROPTLIB::Solvers*)’:
/home/antoine/ROPTLIB//test/DriverJuliaProb.cpp:134:72: error: cannot convert ‘jl_datatype_t* {aka _jl_datatype_t*}’ to ‘jl_value_t* {aka _jl_value_t*}’ for argument ‘1’ to ‘jl_value_t* jl_apply_array_type(jl_value_t*, size_t)’
         jl_value_t* array_type = jl_apply_array_type(jl_float64_type, 1);
                                                                        ^
/home/antoine/ROPTLIB//test/DriverJuliaProb.cpp:147:30: error: ‘jl_is_float64’ was not declared in this scope
         if(jl_is_float64(retx))
                              ^
^CMakefile:126: recipe for target 'JuliaROPTLIB' failed`

**Comment by whuang08** [comment]
Dear Antoine-levitt,

Yes, you need to use  TP=DriverJuliaProb for Julia interface. The binary file given by using option TP=DriverJuliaProb invokes cost function evaluation, gradient evaluation and maybe other functions to perform optimization.

If you only need to test a problem which is written purely in C++ but can be invoked in Julia, then you can use TP=TestSimpleExample and invoke the produced binary.

The latest version ROPTLIB0.6 is tested by Julia 0.5 (see details in the user manual). I have not checked if ROPTLIB works on Julia0.6 yet. I will do this in the next version of ROPTLIB, which will probably be done this summer.

However, it seems that the problem is due to the new version of Julia. Other people also have such problems about the two types "jl_datatype_t" and "jl_value_t". See:
https://github.com/twadleigh/mexjulia/issues/41

Best,

Wen

**Comment by antoine-levitt** [comment]
OK; in the meantime I've got this working with the following patch: https://gist.github.com/antoine-levitt/0b91d17222c770cd613fc20d447f41df.

If anybody wants to run this: apply patch, change path to julia as appropriate, then, in the ROPTLIB directory, run make JuliaROPTLIB, and in julia do Pkg.add("Cxx"), include("Julia/BeginROPTLIB.jl"), and include("Julia/JTestSimpleExample.jl")

**Comment by whuang08** [comment]
Thank you very much for the patch.

Wen
